[[pages]]
path = "pages/0_Login.py"
name = "Login"

[[pages]]
path = "pages/1_home.py"
name = "InÃ­cio"
icon = ":house:"

[[pages]]
path = "pages/2_farms.py"
name = "Fazendas"
icon = "ğŸŒ¾"

[[pages]]
path = "pages/3_pro_carbon.py"
name = "PRO Carbono"
icon = "ğŸŒ¿"

[[pages]]
path = "pages/4_0_commodities.py"
name = "Commodities"
icon = "ğ“‡¢"

[[pages]]
path = "pages/4_1_commodities_farms.py"
name = "Commodities Fazendas"

[[pages]]
path = "pages/4_2_commodities_fields.py"
name = "Commodities TalhÃµes"

[[pages]]
path = "pages/4_3_commodities_fields_new_inventary.py"
name = "Commodities TalhÃµes Novo InventÃ¡rio"

[[pages]]
path = "pages/4_4_commodities_fields_automated_inventary.py"
name = "Commodities InventÃ¡rio Automatizado"

[[pages]]
path = "pages/5_adm_regeneration.py"
name = "ADM RegeneraÃ§Ã£o"
icon = "ğŸŒ"

[[pages]]
path = "pages/6_benefits.py"
name = "BenefÃ­cios"
icon = "ğŸ·ï¸"

[[pages]]
path = "pages/7_users.py"
name = "UsuÃ¡rios"
icon = "ğŸ‘¤"

[[pages]]
path = "pages/8_logout.py"
name = "Sair"
icon = "â¡"
